### ISSUE TITLE
Uploader and renamer doesn't support non-Roman characters

### ISSUE THREAD

**Issue by GaProgMan** [cybercase/webminidisc#10]
## Steps to Recreate

- Create a media file with a series of non-Roman characters
  - i.e. `真夜中のジョーク.mp3`
- Connect minidisc recorded via USB
- Open `https://stefano.brilli.me/webminidisc/` and click `connect`
  - ensuring you select the correct recorder
- Click on the + button and select the file with non-Roman characters
  - i.e. `真夜中のジョーク.mp3`
- Allow the file to sync to the minidisc player
  - Track will be added without a name
- Attempt to rename track, supplying the non-Roman name
 -  Track will not have a name
- Exit from the web app
  - triple dot > Exit
- Await TOC Edit action
- Playback the track on the recorded
- Track will not have a name

## Hardware used

- NETMD MZ-N710
- Brave vLatest
- Pop_OS!

## Assumptions

I have an assumption that either the JS version of FFMPEG used doesn't support non-Roman characters, or that there is some WebAssembly magic happening which wipes out the non-Roman characters.

**Comment by cybercase** [comment]
Hello @GaProgMan  and thanks for the detailed report.

AFAIK, the MiniDisc format uses the Shift JIS encoding to store disc and track's titles.
Here's the map of the characters that in theory we could use: https://en.wikipedia.org/wiki/Shift_JIS#Shift_JIS_byte_map

However, since modern browsers use unicode, I had to apply a function to transform a unicode input provided by the user to a shiftjs one (and vice-versa when reading from the device).
Here's the definition of those transform functions, in the netmdjs project: https://github.com/cybercase/netmd-js/blob/a4a8d9fcb54d5e51e21cc91dc8813e194e67227c/src/utils.ts#L186

Of course, since the unicode charset is way larger that shiftjs, I would have had to handle the case for the user typing characters that are unsupported in the shiftjs encoding (like emoticons or other Japanese non-katakana chars).
This could have been done by replacing unsupported characters with some placeholder character, or by refusing (in the UI) to accept the input as valid if an unsupported character is used.

Because of the challenging task of making this clear to the user, and some lazyness on my end as well :) , I just decided to ignore any non-ascii character
(here's the culprit line https://github.com/cybercase/webminidisc/blob/master/src/services/netmd.ts#L89)

However, if we removed the `sanitizeTitle` function, the encoding function would happily convert all, and only, the supported characters to shiftjs, using the `・` as placeholder for unsupported chars.

We could try this way... I just fear that some users might be surprised by the title not matching exactly what they expected to be (even though this is already the case)... I thought it would have been just easier to say _"sorry, only ascii chars are supported"_ .

Let me know what you think

**Comment by GaProgMan** [comment]
@cybercase: Apologies. I hadn't delved deeply enough into this before posting my issue - I had recieved a replaced NetMD in the mail and got a little too excited to try out the project.

A few hours after posting this issue, I started digging around in the code and removed the `sanitizeTitle` call. It works, in that the characters are witten to the disc. However, they're not converted to ShiftJIS. Since this is likely to not be an issue that a lot of people who use this project have, I'd say that this issue can be closed (then again, you're the repo maintainer).

If I have the time (and can figure it out), I'll look into a way to convert the unicode characters correctly to ShiftJIS. Otherwise, it's a niche issue for a single user.

**Comment by cybercase** [comment]
@GaProgMan no worries. I'm happy to chat about this project :)

By the way, you're right, just removing `sanitizeTitle` is not enough. You might need to set the `wchar` argument of `setTrackTitle` and `setDiscTitle` function to `true` (they're called in `services/netmd.ts` and defined in the netmd-js project)

I'm closing the issue, but reach out to me freely if you need help.
