### ISSUE TITLE
Homebrew mode and MZ-RH910?

### ISSUE THREAD

**Issue by kirbysayshi** [cybercase/webminidisc#122]
I was wondering if I should expect to see any Homebrew features available for the MZ-RH910 when connected and the standard disc is in MD (not Hi-MD) mode. It's unclear to me if it's a matter of the exploits not supporting its firmware or it just needs to be allow-listed in webminidisc pro!

Thank you so much for this wonderful software. I'm so grateful!

**Comment by asivery** [comment]
@kirbysayshi Right now it's not supported at all unfortunately - it's not a matter of simply whitelisting that player yet. I have figured out some things regarding Homebrew mode on them, but I first need to first fix my RH10 to be able to fully test these features.

**Comment by kirbysayshi** [comment]
Thanks for the update! If there's anything I can do to help test, let me know! I'm a developer and have an RH910.

**Comment by asivery** [comment]
@kirbysayshi If you have some time, could you take a look at [this](https://testing.minidisc.wiki/b0824780-3c0c-11ed-b994-2c56dc399093/)? This version should have the core exploits ported over already (TOC download, exploit ATRAC download, things like that). Also, it supports metadata editing and track downloads on HiMD devices.

**Comment by kirbysayshi** [comment]
@asivery great, I'm taking a look now! I saw the in-app changelog, but is there a description of the difference between `Connect to HiMD (Restricted)` vs `(Full)` is?

For all of the below, please don't feel the need to acknowledge all the points. It ended up being more than I anticipated. Most of this is just feedback/observations: if it helps you, great, if it doesn't, ignore it! I won't feel bad and have zero expectations.

Some general notes when using the MZ-RH910:

With a 80min MD disc in the player:

- clicking "Connect" works as expected, and I see "HiMD/NetMD Device" in the USB request dialog window
- clicking "Connect to HiMD (Restricted)" opens up a File Selection (Finder) dialog (?)
- clicking "Connect to HiMD (Full)" shows "No Compatible Devices Found" in the USB request dialog window

With a HiMD disc in the player:

- clicking "Connect" shows "No Compatible Devices Found" in the USB request dialog window
- clicking "Connect to HiMD (Restricted)" opens up a File Selection (Finder) dialog (?)
- clicking "Connect to HiMD (Full)" shows "No Compatible Devices Found" in the USB request dialog window

On mac, I also get the same results even after Ejecting (unmounting) the himd disc from my system (since himd can appear as external drives).

I think this is somewhat typical, but I couldn't get my player with an MD disc inserted to be recognized again by webminidiscpro until I pulled out my usb connect, and waited for the disc to be fully loaded in the player (e.g. see track display info on the device screen), then reconnected USB.

Back to 80min disc results:

- enabling "homebrew mode ripping in the main ui" is shown and works! It's very fast, ~1 minute for a 4m30s track. Much faster than when I tried previous versions of webminidiscpro with my type-r device.
  - A minor note. The transfer window has a slightly surprising order in which it updates. So I figured I'd mention if it was unexpected:
    - "Transferring Track 2", but the progress bar is still at 100% from track 1 and the sectors read something like `4082 sectors of 4082 done (Reading sector 02d2.13...)`
    - after 10-20 seconds: `0%, 0 sectors of XXXX done (Seeking...)`
    - one second or so later: `84%, YYYY sectors of XXXX done (Seeking...)` (or sometimes ~74%, it's always between 70-90% immediately)
    - after 20 seconds or so: 100%, and the title switches to Transferring Track 3
    - repeat the process
- entering homebrew mode and choosing "Archive Disc" is working. The Zip Archive function is also working and is going to be really useful for me! I'm not sure of the implications, but this seems like a nice feature to have in the main UI outside of Homebrew mode.
- Is the Homebrew dialog warning still accurate for HiMD devices? specifically:
  - > After exiting homebrew mode, the player needs to be reset by taking out the batteries. TOC changes won't be applied otherwise. This is important for Type-R devices in particular.
  - And the `To download a track via USB:` section seems like it might be from a much older version (although maybe it's just because this style of downloading is not supported by my himd device?)

I did not try `Switch to HiMD Unrestricted Mode` due to the warning about possibly damaging devices (I only have one HiMD device currently). 

I got an error (page went entirely white) when I tried clicking "Song Recognition" 
<img width="1099" alt="Screenshot 2023-03-11 at 7 14 05 PM" src="https://user-images.githubusercontent.com/90831/224517263-c64dd44e-08ea-4aeb-bcc0-23135f7881c0.png">

I also saw a few errors on page load, which I assume are related more to this being a testing URL: 
<img width="1287" alt="Screenshot 2023-03-11 at 7 19 49 PM" src="https://user-images.githubusercontent.com/90831/224517404-f9343b39-84a4-4090-91fb-e30a77dbd186.png">
<img width="1287" alt="Screenshot 2023-03-11 at 7 19 57 PM" src="https://user-images.githubusercontent.com/90831/224517406-98dd997f-b5cc-4e93-b09a-277ecb7d569e.png">

**Comment by asivery** [comment]
@kirbysayshi Thank you very much for all the points! It helps greatly.
First of all - the difference between HiMD (Restricted) and HiMD (Full) - both of these buttons are responsible for the same thing - HiMD support within Web Minidisc, so the ability to use discs with HiSP / HiLP / LPCM / MP3 recorded on them. For now only track download and metadata editing are supported in both. The first (Restricted) button lets you select the folder where the HiMD device is mounted, since it's a mass storage device in that mode. This mode lets you edit metadata and (in the future) put MP3 audio on HiMD discs. The HiMD (Full) button is tied to the `Switch to HiMD Unrestricted Mode` option in the Homebrew mode, and lets Web Minidisc take complete control over the HiMD device. In the future it will let you do everything the restricted mode lets you do, but also write HiSP, HiLP and PCM audio. For now it is unfinished.

When it comes to your other points:
- Thank you very much for testing the ATRAC download, I am very glad it's working correctly. The transfer window is bugged as you've noticed. I'll fix it in the actual release version, but thank you for the detailed bug report, it will help a lot with troubleshooting
- I will think about adding "Archive Disc" to the main UI. My main concern is that I really do not want to blur the line between homebrew features, and features implemented by Sony. The ATRAC download button in the main UI is an exception to that rule, because I believe it's the most useful and should be more accessible.
- It's best practice to always reset the player after unplugging it from Web Minidisc running homebrew code, and while this warning doesn't really apply to any MD devices at this point, since the homebrew code runs appropriate cleanup upon being unloaded, it's still best practice to take out the batteries and reset the player. It's pretty impossible to tell what the code changes in the player's RAM. When it comes to the rest of that warning, yes it's a relic of an older version of Web Minidisc.
- Thank you for reporting the bug with the song recognition dialog. I'll try to fix it as soon as possible.

Thank you very much for all the testing, and I'll let you know once I write the appropriate bugfixes.

Edit:
Also, please do not test the `HiMD (Full)` mode, since the code responsible for it is even more restricted than the actual `HiMD (Restricted)` mode for now.
I had to implement it in such a roundabout way - splitting the HiMD functionality into 2 different modes - because of WebUSB's security limitations. WebUSB doesn't let applications unload kernel drivers for valid reasons, but when it comes to Minidiscs, that is required (When you record non-MP3 audio on HiMD devices, you need to authorize that audio via lower-level SCSI commands - you can't do that with the mass storage kernel driver loaded).
This is my solution to that problem - clicking the `Switch to HiMD Unrestricted Mode` button redefines the USB descriptors in the HiMD device's memory. It changes the interface class and VID/PID pair. At that point, if you replace the normal MD with a HiMD disc, the device should switch to HiMD mode, which normally would be mass storage, but since that config would have already been overwritten by that button, the device can now be selected using the `HiMD (Full)` USB request dialog window. Unfortunately the downside is that I had to SCSI mass storage device driver in the browser, since it's impossible to rely on the OS for that anymore. This mode will make it possible to implement all the functionalities of SonicStage in Web Minidisc Pro.
For now though, it is entirely unfinished and shouldn't be tested.

**Comment by asivery** [comment]
HiMD machines support homebrew mode since WMDPro v1.4.0.
