### ISSUE TITLE
Support track to pc (MZ-RH1)

### ISSUE THREAD

**Issue by Invictaz** [cybercase/webminidisc#4]
MZ-RH1 has track upload with downloadhack.py. It's buggy but works.

Can you support it? 
Maybe also MP3 to pc (Hi-MD).

**Comment by cybercase** [comment]
Hello @Invictaz .
Unfortunately I don't have a mz-rh1, so I wouldn't know how to work on that feature...

However, if you can find a JS developer that owns a mz-rh1 and is willing to work on that, I'd be happy to give him/her support in adding the feature to webmd.

**Comment by Invictaz** [comment]
@cybercase I have an MZ-RH1 but am not a dev. Also I already saw that someone suggested that you worked together with Gavin to achieve more functionality.
https://github.com/gavinbenda/platinum-md/issues/31

**Comment by cybercase** [comment]
@invictaz Happy to see that @gavinbenda is planning to use netmd-js in his app.
I'm willing to provide any support he needs for this task and, if he wish, to add the track-to-pc feature to netmd-js.

The feature itself shouldn’t be too hard to implement, but keep in mind that since I don’t have a mz-rh1 I can only help with code review, integration and support.
He’ll have to do the development and testing of the new feature by himself, using his own device.

Then, once the track-to-pc support is ready and working in https://github.com/cybercase/netmd-js, I can bring it into WebMiniDisc. I might need some help with testing even for this final task.

**Comment by Invictaz** [comment]
Understood. Well according to this month old article 
https://hn.matthewblode.com/item/22701061

QHiMDTransfer is needing an overhaul. But I don't think the original authors have much free time on their hands to develop. 

What is needed:
-MP3download.c converted to a library that can be used in WebMD / Platinum-MD
-To pc feature (very old downloadhack.py) to be reviewed and converted into a library

Dealing with the 3DES encryption to write ATRAC3Plus to and from Hi-MD is much more difficult.
