### ISSUE TITLE
Security holes of WebUSB

### ISSUE THREAD

**Issue by Invictaz** [cybercase/webminidisc#5]
Mozilla's stance is that webUSB should be avoided. Is there an option to isolate the processing that webminidisc does so that my minidiscs don't get a virus?

https://mozilla.github.io/standards-positions/#webusb

**Comment by cybercase** [comment]
I understand your concerns about security.
Keep in mind that WebUSB has been considered _unsafe_ by mozilla because it allows malicious web developers to send potentially dangerous USB commands to your device.
That's why I made the application open source; so that everyone can see exactly what's going on under the hood.

However, If you don't trust running the web app from the internet, you can clone the repository on your local machine, checkout the version of the source code that you consider safe, and run it locally. In this way, even if someone hacked my account and committed or deployed without my consent a malicious version of the app, you would not be affected.

**Comment by Invictaz** [comment]
Well open-sourcing is only part of the problem. If you run a lot of extra code in Chrome (such as extensions) that they _could_ also have access to the other processes, tabs and windows. Extensions have a Chrome wide implementation and most of them are closed-source. Plus it is unknown to me what other websites do that are running in the background. Can they sniff data via Javascript? A lot of Webkit exploits for gaming consoles escape the sandbox and allow access to the filesystem. 

I really want to love Web Minidisc but for the security I would go to Platinum-MD to avoid RCE.
We saw what happened with Macromedia Flash.

**Comment by cybercase** [comment]
About Chrome Extensions, I suggest to open Chrome in incognito mode so that all the installed extensions are disabled by default.
About background websites, you can make sure to close all the other tabs before running WebMiniDisc so that no other website is running in background.

By the way, I see what you mean.

I honestly think that WebMiniDisc is _reasonably safe_ to use, but we might have different needs. In that case it's absolutely fine if you go for other apps that relies on tech that you trust more.

**Comment by Invictaz** [comment]
Don't get me wrong I love the idea of Web Minidisc. I even have Flash still running, I'm updating JAVA and even use DotNet applications. 

Din't knew about incognito mode. However there are extensions that still work then (if debug flag is enabled) 

Here is a guide to start Chrome in incognito mode: 
https://www.guidingtech.com/directly-launch-chrome-incognito-mode/

It's by adding the "--incognito" tag to the shortcut.

My need is the same as yours, still enjoy this medium. But with some precautions :)
