### ISSUE TITLE
LAM-1 Support

### ISSUE THREAD

**Issue by danmarker7** [cybercase/webminidisc#60]
I wanted to get a desktop solution for using WebMD instead of using my portable unit. I picket up the NetMD compatible unit the LAM-1. When I select connect I can see the LAM-1 listed as "Net MD - Paired" but choose it I get the error: "Unable to set device configuration."

Is there anything I can do to get this unit to play nice with WebMD?

**Comment by cybercase** [comment]
Hello @danmarker7 

Unfortunately I'm not sure I can do anything about this. Another couple of users have reported issues with LAM units, but I cannot debug the issue with such units because I don't own one.

Have you tested your unit with other software like Platinum MD or any release of the linux-minidisc project?

**Comment by danmarker7** [comment]
Thanks for the reply. I was able to record using platinum MD, but it was buggy and didn't complete the record.

Is there any of the other LAM models that play nice with WebMD?

**Comment by cybercase** [comment]
Not one that I know of. Both the LAM-5 and LAM-3 have been reported as not-working in #29

**Comment by asivery** [comment]
@danmarker7 There's been a lot of work done to support the LAMs better. Please let me know if WebMinidisc at https://web.minidisc.wiki/ works better.

**Comment by asivery** [comment]
I have tested the current version on my LAM-1 and haven't encountered any issues.
